name: ðŸŒ Check URLs
on:
  schedule:
    # Every Friday at 16:27 UTC.
    # URLs can decay over time. Setting up a schedule makes it possible to be warned
    # about dead links as soon as possible.
    - cron: "27 16 * * FRI"

jobs:
  check-urls:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v5

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --base .
            --no-progress
            --cache
            --max-cache-age 1d
            --exclude-path _templates/
            --exclude-path classes/
            "**/*.md" "**/*.html" "**/*.rst"

      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
